[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=docker-php-entrypoint entrypoint.sh
autostart=true
autorestart=true
priority=1

[program:mqtt_subscriber]
command=php artisan mqtt:subscribe
directory=/var/www/html
autostart=true
autorestart=true
priority=2
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/html
autostart=true
autorestart=true
priority=3
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
